### PR TITLE
Review my submissions

### PR DESCRIPTION
**Pull request by aayushbisen**
Solved problems using C language. 😃

### CODE REVIEW

**Comment by MadhavBahlMD** [comment]
@aayushbisen the structure is good, good job 💯 

Have you tested the codes ?

**Comment by aayushbisen** [comment]
yes, all codes are working as per problem statements..

**Comment by MadhavBahlMD** [comment]
Great, 💯 ❤️ 
Please do one more thing, in the code files at the top write your name and GitHub handle so that you are given proper credits, 
You can add in this format:
```js
/**
 * author: Aayush Bisen
 * GitHub: https://github.com/aayushbisen/
 */
```
and if you know node then please add yourself as a contributor too by running the following commands
```js
npm i
npm run contributors:add -- aayushbisen code
npm run contributors:generate
```
Thanks :)

**Comment by MadhavBahlMD** [comment]
Looks Good, great work 👍 

Thanks a lot for the contribution, it is appreciated 😃

**Comment by MadhavBahlMD** [comment]
Merged!

**Comment by aayushbisen** [comment]
Added myself as contributor..

**Comment by aayushbisen** [comment]
Are there any other challenges??

**Pull request merged**
